var namespace_unity_1_1_mathematics =
[
    [ "bounds", "struct_unity_1_1_mathematics_1_1bounds.html", "struct_unity_1_1_mathematics_1_1bounds" ],
    [ "BurstPerformanceAttribute", "class_unity_1_1_mathematics_1_1_burst_performance_attribute.html", "class_unity_1_1_mathematics_1_1_burst_performance_attribute" ],
    [ "byte1", "struct_unity_1_1_mathematics_1_1byte1.html", "struct_unity_1_1_mathematics_1_1byte1" ],
    [ "byte2", "struct_unity_1_1_mathematics_1_1byte2.html", "struct_unity_1_1_mathematics_1_1byte2" ],
    [ "byte3", "struct_unity_1_1_mathematics_1_1byte3.html", "struct_unity_1_1_mathematics_1_1byte3" ],
    [ "byte4", "struct_unity_1_1_mathematics_1_1byte4.html", "struct_unity_1_1_mathematics_1_1byte4" ],
    [ "CdsTween", "class_unity_1_1_mathematics_1_1_cds_tween.html", "class_unity_1_1_mathematics_1_1_cds_tween" ],
    [ "color", "struct_unity_1_1_mathematics_1_1color.html", "struct_unity_1_1_mathematics_1_1color" ],
    [ "Constants", "class_unity_1_1_mathematics_1_1_constants.html", "class_unity_1_1_mathematics_1_1_constants" ],
    [ "ConstantShortNames", "class_unity_1_1_mathematics_1_1_constant_short_names.html", "class_unity_1_1_mathematics_1_1_constant_short_names" ],
    [ "ExpTween", "class_unity_1_1_mathematics_1_1_exp_tween.html", "class_unity_1_1_mathematics_1_1_exp_tween" ],
    [ "IMetadataAttribute", "interface_unity_1_1_mathematics_1_1_i_metadata_attribute.html", "interface_unity_1_1_mathematics_1_1_i_metadata_attribute" ],
    [ "IOR", "class_unity_1_1_mathematics_1_1_i_o_r.html", "class_unity_1_1_mathematics_1_1_i_o_r" ],
    [ "mathx", "class_unity_1_1_mathematics_1_1mathx.html", "class_unity_1_1_mathematics_1_1mathx" ],
    [ "MathxAttribute", "class_unity_1_1_mathematics_1_1_mathx_attribute.html", "class_unity_1_1_mathematics_1_1_mathx_attribute" ],
    [ "MyPropertyDescriptor", "class_unity_1_1_mathematics_1_1_my_property_descriptor.html", "class_unity_1_1_mathematics_1_1_my_property_descriptor" ],
    [ "MySampleClass", "class_unity_1_1_mathematics_1_1_my_sample_class.html", "class_unity_1_1_mathematics_1_1_my_sample_class" ],
    [ "MyTypeDescriptionProvider", "class_unity_1_1_mathematics_1_1_my_type_description_provider.html", "class_unity_1_1_mathematics_1_1_my_type_description_provider" ],
    [ "MyTypeDescriptor", "class_unity_1_1_mathematics_1_1_my_type_descriptor.html", "class_unity_1_1_mathematics_1_1_my_type_descriptor" ],
    [ "Polynomial", "class_unity_1_1_mathematics_1_1_polynomial.html", "class_unity_1_1_mathematics_1_1_polynomial" ],
    [ "RandomUtils", "class_unity_1_1_mathematics_1_1_random_utils.html", "class_unity_1_1_mathematics_1_1_random_utils" ],
    [ "ray", "struct_unity_1_1_mathematics_1_1ray.html", "struct_unity_1_1_mathematics_1_1ray" ],
    [ "Rotation", "class_unity_1_1_mathematics_1_1_rotation.html", "class_unity_1_1_mathematics_1_1_rotation" ],
    [ "SDF", "class_unity_1_1_mathematics_1_1_s_d_f.html", "class_unity_1_1_mathematics_1_1_s_d_f" ]
];